apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: jovadrops
type: Opaque
stringData:
  POSTGRES_USER: "jovadrops"
  POSTGRES_PASSWORD: "supersecretpassword"
  POSTGRES_DB: "jovadrops_db"
