apiVersion: v1
kind: Secret
metadata:
  name: jovadrops-secrets
  namespace: jovadrops
type: Opaque
stringData:
  # Connection string format: postgresql://USER:PASSWORD@HOST:PORT/DATABASE
  # Points to the headless postgres service created above
  DATABASE_URL: "postgresql://jovadrops:supersecretpassword@postgres.jovadrops.svc.cluster.local:5432/jovadrops_db?schema=public"
