apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Release.Namespace }}
data:
  NODE_ENV: "{{ .Values.nodeEnv }}"
  NEXT_TELEMETRY_DISABLED: "{{ .Values.nextTelemetryDisabled }}"
