apiVersion: v1
kind: ConfigMap
metadata:
  name: jovadrops-config
  namespace: {{ .Release.Namespace }}
data:
  NODE_ENV: "{{ .Values.nodeEnv }}"
  NEXT_TELEMETRY_DISABLED: "{{ .Values.nextTelemetryDisabled }}"
