{{- if .Values.ingress.enabled }}
{{- $entrypoints := "" }}
{{- if .Values.ingress.annotations }}
  {{- $entrypoints = index .Values.ingress.annotations "traefik.ingress.kubernetes.io/router.entrypoints" | default "" }}
{{- end }}
{{- if .Values.ingress.entrypoint }}
  {{- $entrypoints = .Values.ingress.entrypoint }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.frontend.name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{- if not (and (eq $key "cert-manager.io/cluster-issuer") (eq $entrypoints "web")) }}
    {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if and .Values.ingress.tlsSecretName (not (eq $entrypoints "web")) }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.name }}-svc
                port:
                  number: {{ .Values.service.backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.name }}-svc
                port:
                  number: {{ .Values.service.frontend.port }}
{{- end }}