apiVersion: v1
kind: Secret
metadata:
  name: jovadrops-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
  POSTGRES_USER: "{{ .Values.postgres.user }}"
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.postgres.database }}?schema=public"
  AUTH_SECRET: "{{ .Values.frontend.authSecret }}"
  AUTH_URL: "{{ .Values.frontend.authUrl | default (print "https://" .Values.ingress.host) }}"
  {{- if .Values.frontend.authGoogleId }}
  AUTH_GOOGLE_ID: "{{ .Values.frontend.authGoogleId }}"
  AUTH_GOOGLE_SECRET: "{{ .Values.frontend.authGoogleSecret }}"
  {{- end }}
  {{- if .Values.frontend.authAppleId }}
  AUTH_APPLE_ID: "{{ .Values.frontend.authAppleId }}"
  AUTH_APPLE_SECRET: "{{ .Values.frontend.authAppleSecret }}"
  {{- end }}