apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.frontend.name }}
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.frontend.name }}
  ports:
    - name: http
      port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}
      protocol: TCP
