apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.backend.name }}
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.backend.name }}
  ports:
    - name: http
      port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.targetPort }}
      protocol: TCP
